(()=>{
'use strict';
const CLIENT_ID='697823317404-01qj6tn6qcrklsb251cdup5f7imhaoq3.apps.googleusercontent.com';
const SCOPE='https://www.googleapis.com/auth/drive.readonly';
const FOLDER_NAME='Condomini_APP';
let tokenClient=null,accessToken='';
const escQ=s=>String(s).replace(/'/g,"\\'");
function statusMsg(msg,bad=false){const el=document.getElementById('status');if(el){el.textContent=msg;el.style.color=bad?'#b42318':''}}
function loadGIS(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error('Impossibile caricare accesso Google'));document.head.appendChild(s)})}
async function ensureToken(){await loadGIS();return new Promise((resolve,reject)=>{tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,callback:r=>{if(r.error)return reject(new Error(r.error));accessToken=r.access_token;resolve(accessToken)}});tokenClient.requestAccessToken({prompt:accessToken?'':'consent'})})}
async function driveList(q){let files=[],pageToken='';do{const params={q,fields:'nextPageToken,files(id,name,mimeType,modifiedTime)',orderBy:'name',pageSize:'1000',spaces:'drive'};if(pageToken)params.pageToken=pageToken;const u='https://www.googleapis.com/drive/v3/files?'+new URLSearchParams(params);const r=await fetch(u,{headers:{Authorization:'Bearer '+accessToken}});if(r.status===401){accessToken='';throw new Error('SESSION_EXPIRED')}if(!r.ok)throw new Error('Google Drive: '+r.status);const d=await r.json();files=files.concat(d.files||[]);pageToken=d.nextPageToken||''}while(pageToken);return files}
async function findFolder(){const q=`name='${escQ(FOLDER_NAME)}' and mimeType='application/vnd.google-apps.folder' and trashed=false`;const files=await driveList(q);if(!files.length)throw new Error('Non trovo la cartella '+FOLDER_NAME+' nel tuo Google Drive.');return files[0]}
async function scanCondomini(root){statusMsg('Google Drive collegato · leggo elenco condomini…');const children=await driveList(`'${root.id}' in parents and trashed=false`);const folders=children.filter(f=>f.mimeType==='application/vnd.google-apps.folder');const directExcel=children.filter(f=>/\.(xlsx|xlsm|xls)$/i.test(f.name)).map(f=>({...f,path:FOLDER_NAME+'/'+f.name,condominio:FOLDER_NAME}));const found=[...directExcel];let done=0;await Promise.all(folders.map(async folder=>{done++;statusMsg('Google Drive collegato · controllo condomini… '+done+'/'+folders.length);const inside=await driveList(`'${folder.id}' in parents and trashed=false`);inside.filter(f=>f.mimeType!=='application/vnd.google-apps.folder'&&/\.(xlsx|xlsm|xls)$/i.test(f.name)).forEach(f=>found.push({...f,path:FOLDER_NAME+'/'+folder.name+'/'+f.name,condominio:folder.name}))}));return found.sort((a,b)=>(a.condominio||'').localeCompare(b.condominio||'','it')||a.name.localeCompare(b.name,'it'))}
async function downloadExcel(meta){const r=await fetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(meta.id)+'?alt=media',{headers:{Authorization:'Bearer '+accessToken}});if(!r.ok)throw new Error('Non riesco a scaricare '+meta.name);const b=await r.blob();return new File([b],meta.name,{type:b.type||'application/octet-stream',lastModified:meta.modifiedTime?new Date(meta.modifiedTime).getTime():Date.now()})}
async function refreshDrive(){const btn=document.getElementById('folderBtn');try{if(btn){btn.disabled=true;btn.textContent='AGGIORNAMENTO…'}statusMsg('Collegamento a Google Drive…');if(!accessToken)await ensureToken();const folder=await findFolder();const files=await scanCondomini(folder);if(!files.length)throw new Error('Non trovo file Excel nelle cartelle dei condomini dentro '+FOLDER_NAME+'.');const sel=document.getElementById('condominioSelect'),area=document.getElementById('folderArea');if(sel){sel.innerHTML='';files.forEach((f,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=(f.condominio&&f.condominio!==FOLDER_NAME?f.condominio+' — ':'')+f.name;sel.appendChild(o)})}if(area)area.classList.remove('hidden');statusMsg('Google Drive collegato · '+files.length+' bilanci Excel trovati. Seleziona il condominio e premi “Apri e aggiorna condominio”.');const open=document.getElementById('openSelected');if(open){open.onclick=async e=>{e?.preventDefault?.();try{open.disabled=true;open.textContent='Aggiornamento…';const idx=Number(sel.value||0),meta=files[idx];statusMsg('Scarico '+meta.path+'…');const f=await downloadExcel(meta);await parseFile(f);statusMsg('Aggiornamento completato: '+meta.path)}catch(err){statusMsg(err.message,true);alert(err.message)}finally{open.disabled=false;open.textContent='Apri e aggiorna condominio'}}}}catch(e){if(e.message==='SESSION_EXPIRED'){accessToken='';statusMsg('Sessione Google scaduta. Premi di nuovo AGGIORNA.',true)}else{statusMsg(e.message,true);alert(e.message)}}finally{if(btn){btn.disabled=false;btn.textContent='AGGIORNA'}}}
function setup(){const old=document.getElementById('folderBtn');if(!old)return;const btn=old.cloneNode(true);old.replaceWith(btn);btn.removeAttribute('onclick');btn.textContent='AGGIORNA';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();refreshDrive()},{capture:true});const p=btn.closest('.card')?.querySelector('p.muted');if(p)p.innerHTML='Premi <b>AGGIORNA</b>: il gestionale legge <b>solo le cartelle dei condomini</b> presenti direttamente dentro <b>Condomini_APP</b> e cerca il bilancio Excel in ciascuna cartella.'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();