(()=>{
'use strict';
const CLIENT_ID='697823317404-01qj6tn6qcrklsb251cdup5f7imhaoq3.apps.googleusercontent.com';
const SCOPE='https://www.googleapis.com/auth/drive.readonly';
const FOLDER_NAME='Condomini_APP',FOLDER_MIME='application/vnd.google-apps.folder',TOKEN_KEY='condo_google_token_v1',SYNC_KEY='condo_drive_sync_state_v2';let tokenClient=null,accessToken='',tokenExpiresAt=0;
const escQ=s=>String(s).replace(/'/g,"\\'");const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function statusMsg(msg,bad=false){const el=document.getElementById('status');if(el){el.textContent=msg;el.style.color=bad?'#b42318':'#52606d'}}
function loadSync(){try{return JSON.parse(localStorage.getItem(SYNC_KEY)||'{}')||{}}catch(e){return{}}}function saveSync(x){try{localStorage.setItem(SYNC_KEY,JSON.stringify(x))}catch(e){}}
function restoreToken(){try{const d=JSON.parse(sessionStorage.getItem(TOKEN_KEY)||'null');if(d&&d.token&&Number(d.expiresAt)>Date.now()+60000){accessToken=d.token;tokenExpiresAt=Number(d.expiresAt);return true}}catch(e){}return false}function rememberToken(r){accessToken=r.access_token||'';tokenExpiresAt=Date.now()+Math.max(60,Number(r.expires_in)||3600)*1000;sessionStorage.setItem(TOKEN_KEY,JSON.stringify({token:accessToken,expiresAt:tokenExpiresAt}))}function clearToken(){accessToken='';tokenExpiresAt=0;sessionStorage.removeItem(TOKEN_KEY)}function hasValidToken(){return !!accessToken&&tokenExpiresAt>Date.now()+60000}
function loadGIS(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error('Impossibile caricare accesso Google'));document.head.appendChild(s)})}async function ensureToken(){if(hasValidToken()||restoreToken())return accessToken;await loadGIS();return new Promise((resolve,reject)=>{tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,include_granted_scopes:true,callback:r=>{if(r.error)return reject(new Error(r.error));rememberToken(r);resolve(accessToken)}});tokenClient.requestAccessToken({prompt:''})})}
async function driveList(q){let files=[],pageToken='';do{const params={q,fields:'nextPageToken,files(id,name,mimeType,modifiedTime,parents)',orderBy:'name',pageSize:'1000',spaces:'drive'};if(pageToken)params.pageToken=pageToken;const r=await fetch('https://www.googleapis.com/drive/v3/files?'+new URLSearchParams(params),{headers:{Authorization:'Bearer '+accessToken}});if(r.status===401){clearToken();throw new Error('SESSION_EXPIRED')}if(!r.ok)throw new Error('Google Drive: '+r.status);const d=await r.json();files=files.concat(d.files||[]);pageToken=d.nextPageToken||''}while(pageToken);return files}
async function findFolder(){const files=await driveList(`name='${escQ(FOLDER_NAME)}' and mimeType='${FOLDER_MIME}' and trashed=false`);if(!files.length)throw new Error('Non trovo la cartella '+FOLDER_NAME+' nel tuo Google Drive.');files.sort((a,b)=>new Date(b.modifiedTime||0)-new Date(a.modifiedTime||0));return files[0]}
function isExcel(f){return f.mimeType!==FOLDER_MIME&&/\.(xlsx|xlsm|xls)$/i.test(f.name)}function yearValue(s){const m=String(s||'').match(/(?:19|20)\d{2}/g);return m?Math.max(...m.map(Number)):0}function scoreCandidate(c){const p=c.path.join('/').toLowerCase();let score=0;if(c.path.some(x=>/^bilancio$/i.test(String(x).trim())))score+=100000;if(c.path.some(x=>/^(?:19|20)\d{2}$/.test(String(x).trim())))score+=50000;score+=yearValue(p)*100+yearValue(c.file.name)*1000+new Date(c.file.modifiedTime||0).getTime()/1e12;return score}
async function collectExcel(folder,maxDepth=5){const out=[];async function walk(id,path,depth){const items=await driveList(`'${id}' in parents and trashed=false`);for(const f of items){if(isExcel(f))out.push({file:f,path});else if(f.mimeType===FOLDER_MIME&&depth<maxDepth)await walk(f.id,path.concat(f.name),depth+1)}}await walk(folder.id,[],0);return out}
function chooseBalance(candidates){if(!candidates.length)return{state:'missing',balance:null,excel:[]};const preferred=candidates.filter(c=>c.path.some(x=>/^bilancio$/i.test(String(x).trim()))),pool=preferred.length?preferred:candidates;pool.sort((a,b)=>scoreCandidate(b)-scoreCandidate(a));return{state:'ok',balance:pool[0].file,excel:candidates.map(c=>c.file),balancePath:pool[0].path}}
async function scanCondomini(root){statusMsg('Google Drive collegato · controllo rapido dei condomini…');const children=await driveList(`'${root.id}' in parents and trashed=false`),folders=children.filter(f=>f.mimeType===FOLDER_MIME).sort((a,b)=>a.name.localeCompare(b.name,'it')),rows=new Array(folders.length);let next=0,done=0;async function worker(){while(true){const i=next++;if(i>=folders.length)return;const folder=folders[i];try{rows[i]={folder,...chooseBalance(await collectExcel(folder,5))}}catch(e){rows[i]={folder,state:'error',error:e};}done++;statusMsg('Controllo bilanci '+done+'/'+folders.length+'…')}}await Promise.all(Array.from({length:Math.min(4,folders.length)},worker));return rows}
async function downloadExcel(meta){const r=await fetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(meta.id)+'?alt=media',{headers:{Authorization:'Bearer '+accessToken}});if(r.status===401){clearToken();throw new Error('SESSION_EXPIRED')}if(!r.ok)throw new Error('Non riesco a scaricare '+meta.name);const b=await r.blob();return new File([b],meta.name,{type:b.type||'application/octet-stream',lastModified:meta.modifiedTime?new Date(meta.modifiedTime).getTime():Date.now()})}
function ensureArea(){let area=document.getElementById('driveCondoArea');if(area)return area;area=document.createElement('div');area.id='driveCondoArea';const status=document.getElementById('status');status?.parentNode?.insertBefore(area,status.nextSibling);return area}
function renderRows(rows,updated=0,failed=[],skipped=0){const area=ensureArea(),ok=rows.filter(r=>r.state==='ok');area.innerHTML='<div>Condomini: '+rows.length+' · aggiornati: '+updated+' · invariati: '+skipped+'</div><select id="driveCondoSelect"></select><button id="driveOpenCondo">APRI CONDOMINIO</button>';const sel=document.getElementById('driveCondoSelect');ok.forEach((r,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=r.folder.name;sel.appendChild(o)});document.getElementById('driveOpenCondo').onclick=async()=>{const r=ok[Number(sel.value||0)];try{window.condoSetFolderTitle?.(r.folder.name);const f=await downloadExcel(r.balance);await parseFile(f);statusMsg('Aperto: '+r.folder.name)}finally{window.condoClearFolderTitle?.()}}}
function sig(r){return [r.balance?.id||'',r.balance?.modifiedTime||'',r.balance?.name||''].join('|')}
async function bulkUpdate(rows){const ok=rows.filter(r=>r.state==='ok'),state=loadSync();let updated=0,skipped=0;const failed=[];for(let i=0;i<ok.length;i++){const r=ok[i],key=r.folder.id||r.folder.name,currentSig=sig(r);if(state[key]===currentSig){skipped++;statusMsg('Nessuna modifica: '+r.folder.name+' ('+(i+1)+'/'+ok.length+')');continue}try{statusMsg('Aggiorno '+r.folder.name+' ('+(i+1)+'/'+ok.length+')…');window.condoSetFolderTitle?.(r.folder.name);const f=await downloadExcel(r.balance);await parseFile(f);state[key]=currentSig;saveSync(state);updated++}catch(e){console.error(e);failed.push(r.folder.name)}finally{window.condoClearFolderTitle?.()}}renderRows(rows,updated,failed,skipped);return{updated,failed,skipped}}
async function doRefresh(){const root=await findFolder(),rows=await scanCondomini(root);const result=await bulkUpdate(rows);statusMsg('Aggiornamento completato · '+result.updated+' modificati · '+result.skipped+' già aggiornati'+(result.failed.length?' · '+result.failed.length+' da verificare':'')+'.')}
async function refreshDrive(){const btn=document.getElementById('folderBtn');try{if(btn){btn.disabled=true;btn.textContent='AGGIORNAMENTO…'}statusMsg('Collegamento a Google Drive…');await ensureToken();await doRefresh()}catch(e){statusMsg(e.message,true);alert(e.message)}finally{if(btn){btn.disabled=false;btn.textContent='AGGIORNA'}}}
function setup(){restoreToken();const old=document.getElementById('folderBtn');if(!old)return;const btn=old.cloneNode(true);old.replaceWith(btn);btn.removeAttribute('onclick');btn.textContent='AGGIORNA';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();refreshDrive()},{capture:true});const p=btn.closest('.card')?.querySelector('p.muted');if(p)p.innerHTML='Premi <b>AGGIORNA</b>: controllo rapido su Google Drive. I bilanci invariati vengono saltati; vengono ricalcolati solo quelli modificati.'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();