(()=>{
'use strict';
const CLIENT_ID='697823317404-01qj6tn6qcrklsb251cdup5f7imhaoq3.apps.googleusercontent.com';
const SCOPE='https://www.googleapis.com/auth/drive.readonly';
const FOLDER_NAME='Condomini_APP';
const FOLDER_MIME='application/vnd.google-apps.folder';
let tokenClient=null,accessToken='';
const escQ=s=>String(s).replace(/'/g,"\\'");
function statusMsg(msg,bad=false){const el=document.getElementById('status');if(el){el.textContent=msg;el.style.color=bad?'#b42318':'#52606d'}}
function loadGIS(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error('Impossibile caricare accesso Google'));document.head.appendChild(s)})}
async function ensureToken(interactive=false){await loadGIS();return new Promise((resolve,reject)=>{tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,include_granted_scopes:true,callback:r=>{if(r.error)return reject(new Error(r.error));accessToken=r.access_token;resolve(accessToken)}});tokenClient.requestAccessToken({prompt:interactive?'select_account':''})})}
async function driveList(q){let files=[],pageToken='';do{const params={q,fields:'nextPageToken,files(id,name,mimeType,modifiedTime,parents)',orderBy:'name',pageSize:'1000',spaces:'drive'};if(pageToken)params.pageToken=pageToken;const u='https://www.googleapis.com/drive/v3/files?'+new URLSearchParams(params);const r=await fetch(u,{headers:{Authorization:'Bearer '+accessToken}});if(r.status===401){accessToken='';throw new Error('SESSION_EXPIRED')}if(!r.ok)throw new Error('Google Drive: '+r.status);const d=await r.json();files=files.concat(d.files||[]);pageToken=d.nextPageToken||''}while(pageToken);return files}
async function findFolder(){const files=await driveList(`name='${escQ(FOLDER_NAME)}' and mimeType='${FOLDER_MIME}' and trashed=false`);if(!files.length)throw new Error('Non trovo la cartella '+FOLDER_NAME+' nel tuo Google Drive.');return files[0]}
function isExcel(f){return f.mimeType!==FOLDER_MIME&&/\.(xlsx|xlsm|xls)$/i.test(f.name)}
function yearValue(s){const m=String(s||'').match(/(?:19|20)\d{2}/g);return m?Math.max(...m.map(Number)):0}
function scoreCandidate(c){const p=c.path.join('/').toLowerCase();let score=0;if(c.path.some(x=>/^bilancio$/i.test(String(x).trim())))score+=100000;if(c.path.some(x=>/^(?:19|20)\d{2}$/.test(String(x).trim())))score+=50000;score+=yearValue(p)*100;score+=yearValue(c.file.name)*1000;score+=new Date(c.file.modifiedTime||0).getTime()/1e12;return score}
async function collectExcel(folder,maxDepth=5){const out=[];async function walk(id,path,depth){const items=await driveList(`'${id}' in parents and trashed=false`);for(const f of items){if(isExcel(f)){out.push({file:f,path})}else if(f.mimeType===FOLDER_MIME&&depth<maxDepth){await walk(f.id,path.concat(f.name),depth+1)}}}await walk(folder.id,[],0);return out}
function chooseBalance(candidates){if(!candidates.length)return{state:'missing',balance:null,excel:[]};const preferred=candidates.filter(c=>c.path.some(x=>/^bilancio$/i.test(String(x).trim())));const pool=preferred.length?preferred:candidates;pool.sort((a,b)=>scoreCandidate(b)-scoreCandidate(a));return{state:'ok',balance:pool[0].file,excel:candidates.map(c=>c.file),balancePath:pool[0].path}}
async function scanCondomini(root){statusMsg('Google Drive collegato · leggo le cartelle dei condomini…');const children=await driveList(`'${root.id}' in parents and trashed=false`);const folders=children.filter(f=>f.mimeType===FOLDER_MIME).sort((a,b)=>a.name.localeCompare(b.name,'it'));const rows=[];for(let i=0;i<folders.length;i++){const folder=folders[i];statusMsg('Google Drive collegato · cerco il bilancio di '+folder.name+' ('+(i+1)+'/'+folders.length+')');const candidates=await collectExcel(folder,5);rows.push({folder,...chooseBalance(candidates)})}return rows}
async function downloadExcel(meta){const r=await fetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(meta.id)+'?alt=media',{headers:{Authorization:'Bearer '+accessToken}});if(!r.ok)throw new Error('Non riesco a scaricare '+meta.name);const b=await r.blob();return new File([b],meta.name,{type:b.type||'application/octet-stream',lastModified:meta.modifiedTime?new Date(meta.modifiedTime).getTime():Date.now()})}
function ensureArea(){let area=document.getElementById('driveCondoArea');if(area)return area;area=document.createElement('div');area.id='driveCondoArea';area.style.cssText='margin-top:16px';const status=document.getElementById('status');status?.parentNode?.insertBefore(area,status.nextSibling);return area}
function renderRows(rows){const area=ensureArea();const ok=rows.filter(r=>r.state==='ok');const missing=rows.filter(r=>r.state==='missing');area.innerHTML='<div style="font-weight:800;margin:8px 0">Condomini trovati: '+rows.length+' · Pronti: '+ok.length+'</div><select id="driveCondoSelect" style="width:100%;padding:13px;border:1px solid #ccd4df;border-radius:10px;font-size:16px;background:white"></select><button id="driveOpenCondo" style="width:100%;margin-top:10px;padding:14px;border:0;border-radius:10px;background:#174a7a;color:white;font-weight:800;font-size:16px">APRI E AGGIORNA CONDOMINIO</button>'+(missing.length?'<div style="margin-top:10px;font-size:13px;color:#8a4b08"><b>Senza bilancio Excel:</b> '+missing.map(r=>r.folder.name).join(', ')+'</div>':'');const sel=document.getElementById('driveCondoSelect');ok.forEach((r,i)=>{const o=document.createElement('option');o.value=String(i);const path=(r.balancePath||[]).length?(r.balancePath.join(' › ')+' › '):'';o.textContent=r.folder.name+' — '+path+r.balance.name;sel.appendChild(o)});const open=document.getElementById('driveOpenCondo');if(!ok.length){open.disabled=true;open.textContent='NESSUN CONDOMINIO PRONTO';return}open.onclick=async()=>{const r=ok[Number(sel.value||0)];try{open.disabled=true;open.textContent='AGGIORNAMENTO…';statusMsg('Scarico '+r.folder.name+' / '+r.balance.name+'…');const f=await downloadExcel(r.balance);await parseFile(f);statusMsg('Aggiornato: '+r.folder.name+' — '+r.balance.name)}catch(e){statusMsg(e.message,true);alert(e.message)}finally{open.disabled=false;open.textContent='APRI E AGGIORNA CONDOMINIO'}}}
async function refreshDrive(){const btn=document.getElementById('folderBtn');try{if(btn){btn.disabled=true;btn.textContent='AGGIORNAMENTO…'}statusMsg('Collegamento a Google Drive…');if(!accessToken)await ensureToken(false);const root=await findFolder();const rows=await scanCondomini(root);renderRows(rows);const ok=rows.filter(r=>r.state==='ok').length;statusMsg('Controllo completato · '+rows.length+' condomini · '+ok+' pronti.')}catch(e){if(e.message==='SESSION_EXPIRED'){accessToken='';statusMsg('Sessione Google scaduta. Premi di nuovo AGGIORNA per ricollegarti.',true)}else{statusMsg(e.message,true);alert(e.message)}}finally{if(btn){btn.disabled=false;btn.textContent='AGGIORNA'}}}
function setup(){const old=document.getElementById('folderBtn');if(!old)return;const btn=old.cloneNode(true);old.replaceWith(btn);btn.removeAttribute('onclick');btn.textContent='AGGIORNA';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();refreshDrive()},{capture:true});const p=btn.closest('.card')?.querySelector('p.muted');if(p)p.innerHTML='Premi <b>AGGIORNA</b>: il gestionale entra automaticamente nelle cartelle dei condomini, cerca <b>Bilancio</b>, le sottocartelle degli anni e individua il bilancio Excel più recente.'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();