(()=>{
'use strict';
const MONTHS={GEN:['Gennaio',1],GENNAIO:['Gennaio',1],FEB:['Febbraio',2],FEBBRAIO:['Febbraio',2],MAR:['Marzo',3],MARZO:['Marzo',3],APR:['Aprile',4],APRILE:['Aprile',4],MAG:['Maggio',5],MAGGIO:['Maggio',5],GIU:['Giugno',6],GIUGNO:['Giugno',6],LUG:['Luglio',7],LUGLIO:['Luglio',7],AGO:['Agosto',8],AGOSTO:['Agosto',8],SET:['Settembre',9],SETT:['Settembre',9],SETTEMBRE:['Settembre',9],OTT:['Ottobre',10],OTTOBRE:['Ottobre',10],NOV:['Novembre',11],NOVEMBRE:['Novembre',11],DIC:['Dicembre',12],DICEMBRE:['Dicembre',12]};
const IGNORE=['FRONTESPIZIO','FROTESPIZIO','RENDICONTO','CONTO ECONOMICO','STATO PATRIMONIALE','SITUAZIONE PATRIMONIALE','PRIMA NOTA','MILLESIMI','PREVENTIVO SPESA','RIPARTO SPESA','MOROSI','RATE INSOLUTE','RESOCONTO'];
const ALLOWED_OTHER=/CONG|REC.*INCASS|PRECEDENT|STRAORD|FONDO|CAUSA|LAVOR/i;
const nrm=x=>String(x??'').trim().replace(/\s+/g,' ').toUpperCase();
const canon=x=>nrm(x).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9]+/g,' ').trim();
const r2=x=>Math.round((Number(x)||0)*100)/100;
function num(x){if(typeof x==='number'&&Number.isFinite(x))return x;if(typeof x==='string'){let v=x.trim();if(!v)return 0;if(v.includes(',')&&v.includes('.'))v=v.replace(/\./g,'').replace(',','.');else if(v.includes(','))v=v.replace(',','.');const z=parseFloat(v);return Number.isFinite(z)?z:0}return 0}
function rowsOf(wb,name){return XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true})}
function headers(rows,hi){const a=hi>0?(rows[hi-1]||[]):[],b=rows[hi]||[],H=[];for(let i=0;i<Math.max(a.length,b.length);i++)H[i]=(b[i]!==null&&b[i]!==undefined&&b[i]!=='')?b[i]:a[i];return H}
function colExact(H,...names){const hs=H.map(nrm);for(const name of names){const i=hs.indexOf(nrm(name));if(i>=0)return i}return -1}
function colContains(H,...terms){const hs=H.map(nrm);for(const t of terms){const k=nrm(t);for(let i=0;i<hs.length;i++)if(hs[i].includes(k))return i}return -1}
function monthInfo(v){const k=nrm(v);return MONTHS[k]?{label:MONTHS[k][0],month:MONTHS[k][1]}:null}
function monthSequence(H){const cols=[];for(let i=0;i<H.length;i++){const m=monthInfo(H[i]);if(m)cols.push({col:i,dateCol:nrm(H[i+1]).startsWith('DATA')?i+1:null,...m})}let best=[];for(let s=0;s<cols.length;s++){let q=[cols[s]],prev=cols[s].month;for(let i=s+1;i<cols.length&&q.length<12;i++){const exp=prev===12?1:prev+1;if(cols[i].month!==exp)break;q.push(cols[i]);prev=cols[i].month}if(q.length>best.length)best=q;if(q.length===12)break}return best.length===12?best:[]}
function isHeaderRow(row){const h=(row||[]).map(nrm);return (h.includes('NOMINATIVO')||h.includes('CONDOMINO'))&&h.includes('RATA')&&monthSequence(row||[]).length===12}
function headerBlocks(rows){const out=[];for(let i=0;i<rows.length;i++)if(isHeaderRow(rows[i]))out.push(i);return out}
function isSummary(name){const x=nrm(name);return !x||x==='TOTALI'||x.startsWith('TOTALE')||x.includes('ANCORA DA INCASSARE')||x.includes('TOTALE DA INCASSARE')||x.includes('TOTALE INCASSI')||x.includes('DA REGISTRARE')}
function yearPair(s){let m=String(s||'').match(/((?:19|20)\d{2})\s*[-_/]\s*(?:(?:19|20)?(\d{2,4}))/);if(!m)return null;return +m[1]}
function yearForInc(inc,fileName){return yearPair(inc)||yearPair(window.condoSourcePath||'')||yearPair(fileName||'')}
function assignYears(seq,inc,fileName){let startYear=yearForInc(inc,fileName),startMonth=seq[0].month;if(!startYear){const now=new Date();startYear=(now.getMonth()+1)>=startMonth?now.getFullYear():now.getFullYear()-1}const now=new Date();return seq.map((m,i)=>{const abs=startYear*12+(startMonth-1)+i,year=Math.floor(abs/12),month=abs%12+1,due=year<now.getFullYear()||(year===now.getFullYear()&&month<=now.getMonth()+1);return{...m,year,month,due}})}
function frontTitle(wb,fileName){const sn=(wb.SheetNames||[]).find(s=>/FRO?NT?ESPIZIO/i.test(s));if(sn){const rr=rowsOf(wb,sn);for(const row of rr.slice(0,10))for(const v of row||[]){if(v&&/CONDOMINIO/i.test(String(v)))return String(v).replace(/CONDOMINIO/i,'').replace(/^[ \"-]+|[ \"-]+$/g,'').trim()}}return String(fileName||'Condominio').replace(/\.(xlsx|xlsm|xls)$/i,'')}
function rateHeaders(rows){const a=[];for(let i=0;i<rows.length;i++){const h=(rows[i]||[]).map(nrm);if((h.includes('NOMINATIVO')||h.includes('CONDOMINO'))&&h.includes('RATA'))a.push(i)}return a}
function fallbackRates(wb){const vals=new Map(),dups=new Set();for(const sn of wb.SheetNames||[]){if(!/RIPARTO/i.test(sn))continue;const rows=rowsOf(wb,sn),his=rateHeaders(rows);for(let z=0;z<his.length;z++){const hi=his[z],end=z+1<his.length?his[z+1]:rows.length,H=headers(rows,hi),nc=colExact(H,'NOMINATIVO','CONDOMINO'),rc=colExact(H,'RATA');if(nc<0||rc<0)continue;for(let j=hi+1;j<end;j++){const name=String(rows[j]?.[nc]??'').trim();if(isSummary(name))continue;const k=canon(name),r=num(rows[j]?.[rc]);if(!k||r<=0)continue;if(vals.has(k))dups.add(k);else vals.set(k,r)}}}dups.forEach(k=>vals.delete(k));return vals}
function exactPerson(name,people){const key=canon(name);if(!key)return null;const a=people.filter(x=>canon(x.name)===key);return a.length===1?a[0]:null}
function suspiciousRate(row,months,rata){const vals=months.map(m=>r2(Math.max(0,num(row[m.col])))).filter(v=>v>0);if(vals.length<6)return null;const freq=new Map();for(const v of vals)freq.set(v,(freq.get(v)||0)+1);let mode=0,count=0;for(const [v,c] of freq)if(c>count){mode=v;count=c}if(count/vals.length>=.75&&Math.abs(mode-r2(rata))>.01)return mode;return null}
function otherHeaders(rows){const a=[];for(let i=0;i<rows.length;i++){const h=(rows[i]||[]).map(nrm);if((h.includes('NOMINATIVO')||h.includes('CONDOMINO'))&&h.some(x=>x.includes('DA INCASSARE')||x.includes('ANCORA DA INCASSARE')||x.includes('CONGUAGLIO')||x.includes('SALDO')||x.includes('IMPORTO')))a.push(i)}return a}
function parseOtherSheet(sn,rows,people){if(!ALLOWED_OTHER.test(nrm(sn)))return;const his=otherHeaders(rows);for(let z=0;z<his.length;z++){const hi=his[z],end=z+1<his.length?his[z+1]:rows.length,H=headers(rows,hi),nc=colExact(H,'NOMINATIVO','CONDOMINO');if(nc<0)continue;const bc=colContains(H,'DA INCASSARE','ANCORA DA INCASSARE','RESIDUO','SALDO'),duec=colContains(H,'CONGUAGLIO','IMPORTO','DA VERSARE','TOTALE'),paidc=colContains(H,'INCASSATO','PAGATO','VERSATO'),reimbc=colContains(H,'RIMBORSATO'),isCong=/CONG|REC.*INCASS|PRECEDENT/i.test(nrm(sn));for(let j=hi+1;j<end;j++){const row=rows[j],name=String(row?.[nc]??'').trim();if(isSummary(name))continue;const p=exactPerson(name,people);if(!p)continue;let bal=bc>=0?num(row[bc]):0;if(bc<0&&duec>=0)bal=num(row[duec])-(paidc>=0?num(row[paidc]):0)+(reimbc>=0?num(row[reimbc]):0);if(Math.abs(bal)<=.01)continue;if(bal>0)p.items.push({type:isCong?'cong':'extra',label:isCong?'Conguaglio a debito':sn,amount:r2(bal),selected:false});else p.credits.push({label:isCong?'Conguaglio / dare-avere a credito':'Credito / eccedenza – '+sn,amount:r2(-bal),selected:false})}}}
function analyzeV7(wb,fileName){const inc=(wb.SheetNames||[]).find(s=>nrm(s).startsWith('INCASSI')&&!/STRAORD/i.test(nrm(s)));if(!inc)throw new Error('Non trovo il foglio Incassi ordinari.');const rows=rowsOf(wb,inc),his=headerBlocks(rows);if(!his.length)throw new Error('Non riconosco con sicurezza le intestazioni del foglio '+inc+'.');const fallback=fallbackRates(wb),people=[],blockMonths=[];
 for(let b=0;b<his.length;b++){const hi=his[b],end=b+1<his.length?his[b+1]:rows.length,H=headers(rows,hi),nc=colExact(H,'NOMINATIVO','CONDOMINO'),rc=colExact(H,'RATA'),sc=colExact(H,'SCALA','SC','S'),pc=colExact(H,'P','PIANO'),ic=colExact(H,'INT','INT.','INTERNO'),indc=colContains(H,'SPESE INDIVIDUALI'),indpaid=colContains(H,'RISCOSSIONE','RISCOSSE'),seq=monthSequence(H);if(nc<0||seq.length!==12)continue;const months=assignYears(seq,inc,fileName);blockMonths.push(months);
  for(let j=hi+1;j<end;j++){const row=rows[j]||[],name=String(row[nc]??'').trim();if(isSummary(name))continue;let rata=rc>=0?num(row[rc]):0;if(rata<=0)rata=fallback.get(canon(name))||0;const p={id:people.length,name,scala:sc>=0?String(row[sc]??''):'',piano:pc>=0?String(row[pc]??''):'',interno:ic>=0?String(row[ic]??''):'',phone:'',email:'',items:[],credits:[],conflicts:[],recipientAddress:'',_v7:{inc,rata,months,block:b+1,row:j+1}};
   if(rata<=0)p.conflicts.push('DA VERIFICARE: rata ordinaria non determinabile con certezza.');else{const mode=suspiciousRate(row,months,rata);if(mode!=null)p.conflicts.push('DA VERIFICARE: rata '+r2(rata)+' € ma pagamenti ricorrenti '+mode+' €. Nessun insoluto ordinario calcolato automaticamente.');else for(const m of months){if(!m.due)continue;const paid=Math.max(0,num(row[m.col])),diff=r2(rata-paid);if(Math.abs(diff)<=.01)continue;p.items.push({type:'ordinary',label:m.label+' '+m.year,amount:diff,selected:false,_ordinary:true,_negative:diff<0})}}
   if(indc>=0){const due=Math.max(0,num(row[indc])),paid=indpaid>=0?Math.max(0,num(row[indpaid])):0,diff=r2(due-paid);if(diff>.01)p.items.push({type:'extra',label:'Spese individuali',amount:diff,selected:false});else if(diff<-.01)p.credits.push({label:'Eccedenza spese individuali',amount:r2(-diff),selected:false})}people.push(p)} }
 for(const sn of wb.SheetNames||[]){const nn=nrm(sn);if(sn===inc||IGNORE.some(x=>nn.includes(x)))continue;parseOtherSheet(sn,rowsOf(wb,sn),people)}
 people.forEach((p,i)=>{p.id=i;p.items=p.items.map(x=>({...x,selected:false}));p.credits=p.credits.map(x=>({...x,selected:false}));p._v7.gross=r2(p.items.reduce((s,x)=>s+(x.amount>0?x.amount:0),0))});return{title:frontTitle(wb,fileName),people,inc,months:blockMonths[0]||[],blocks:his.length}
}
const oldRenderPerson=window.renderPerson;
if(typeof oldRenderPerson==='function')window.renderPerson=function(p){oldRenderPerson(p);const box=document.getElementById('p'+p.id);if(!box)return;const ord=(p.items||[]).filter(x=>x.type==='ordinary'),sec=[...box.querySelectorAll('.section')].find(s=>(s.querySelector('h4')?.textContent||'').trim()==='Rate ordinarie scoperte');if(sec){const h=sec.querySelector('h4');if(h)h.textContent='Rate ordinarie';[...sec.querySelectorAll('.item')].forEach((el,i)=>{const x=ord[i],amt=el.querySelector('.amt');if(x&&amt&&x.amount<0){amt.textContent='− '+euro(Math.abs(x.amount));amt.style.color='#c62828';amt.style.fontWeight='900'}})}if(p.conflicts?.length){const w=document.createElement('div');w.style.cssText='margin:10px 0;padding:10px;border-radius:10px;background:#fff3cd;color:#7a5200;font-weight:800';w.textContent=p.conflicts.join(' ');box.prepend(w)}};
const oldMessage=window.message;
if(typeof oldMessage==='function')window.message=function(p){const condo=building.textContent.trim()||'Condominio';let lines=['Salve, '+condo,'Siamo a ricordarle il versamento delle seguenti rate condominiali.',''];(p.items||[]).filter(x=>x.selected).forEach(x=>lines.push(`• ${x.label}: ${x.amount<0?'− ':''}${euro(Math.abs(x.amount))}`));const c=calc(p);lines.push('',`TOTALE SELEZIONATO: ${c.gross<0?'− ':''}${euro(Math.abs(c.gross))}`);const cc=(p.credits||[]).filter(x=>x.selected);if(cc.length){lines.push('','COMPENSAZIONI SELEZIONATE:');cc.forEach(x=>lines.push(`• ${x.label}: − ${euro(x.amount)}`));lines.push(`NUOVO TOTALE DOPO COMPENSAZIONE: ${c.net<0?'− ':''}${euro(Math.abs(c.net))}`)}lines.push('','Qualora abbia già provveduto, ritenga nullo il presente promemoria.','Saluti');return lines.join('\n')};
async function parseFileV7(file){loader.classList.remove('hidden');results.classList.add('hidden');try{const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array',cellDates:true,cellFormula:true}),r=analyzeV7(wb,file.name);current=r.people;if(!wb.Sheets.Frotespizio){const front=(wb.SheetNames||[]).find(s=>/FRO?NT?ESPIZIO/i.test(s));if(front)wb.Sheets.Frotespizio=wb.Sheets[front];else wb.Sheets.Frotespizio=XLSX.utils.aoa_to_sheet([[r.title]]);if(!wb.SheetNames.includes('Frotespizio'))wb.SheetNames.push('Frotespizio')}render(file.name,wb);building.textContent=r.title;source.textContent='Motore V7 strutturale · '+r.blocks+' blocchi Incassi · solo rate scadute';const v=document.querySelector('#results .card .muted');if(v)v.textContent='Lettura strutturale · ordine Excel preservato · mese contro stesso mese · dati ambigui = DA VERIFICARE'}catch(e){console.error(e);alert('Controllo bilancio: '+e.message);throw e}finally{loader.classList.add('hidden')}}
window.condoAnalyzeV7=analyzeV7;parseFile=parseFileV7;
})();
