(()=>{
'use strict';
const MONTHS={GEN:['Gennaio',1],GENNAIO:['Gennaio',1],FEB:['Febbraio',2],FEBBRAIO:['Febbraio',2],MAR:['Marzo',3],MARZO:['Marzo',3],APR:['Aprile',4],APRILE:['Aprile',4],MAG:['Maggio',5],MAGGIO:['Maggio',5],GIU:['Giugno',6],GIUGNO:['Giugno',6],LUG:['Luglio',7],LUGLIO:['Luglio',7],AGO:['Agosto',8],AGOSTO:['Agosto',8],SET:['Settembre',9],SETT:['Settembre',9],SETTEMBRE:['Settembre',9],OTT:['Ottobre',10],OTTOBRE:['Ottobre',10],NOV:['Novembre',11],NOVEMBRE:['Novembre',11],DIC:['Dicembre',12],DICEMBRE:['Dicembre',12]};
const IGNORE=['FRONTESPIZIO','FROTESPIZIO','RENDICONTO','CONTO ECONOMICO','STATO PATRIMONIALE','SITUAZIONE PATRIMONIALE','PRIMA NOTA','MILLESIMI','PREVENTIVO SPESA','RIPARTO SPESA','MOROSI','RATE INSOLUTE','RESOCONTO'];
const ALLOWED_OTHER=/CONG|REC.*INCASS|PRECEDENT|STRAORD|FONDO|CAUSA|LAVOR/i;
const nrm=x=>String(x??'').trim().replace(/\s+/g,' ').toUpperCase(),canon=x=>nrm(x).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9]+/g,' ').trim(),r2=x=>Math.round((Number(x)||0)*100)/100;
function num(x){if(typeof x==='number'&&Number.isFinite(x))return x;if(typeof x==='string'){let v=x.trim();if(!v)return 0;if(v.includes(',')&&v.includes('.'))v=v.replace(/\./g,'').replace(',','.');else if(v.includes(','))v=v.replace(',','.');const z=parseFloat(v);return Number.isFinite(z)?z:0}return 0}
function rowsOf(wb,n){return XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:null,raw:true})}
function headers(rows,hi){const a=hi>0?(rows[hi-1]||[]):[],b=rows[hi]||[],H=[];for(let i=0;i<Math.max(a.length,b.length);i++)H[i]=(b[i]!==null&&b[i]!==undefined&&b[i]!=='')?b[i]:a[i];return H}
function colExact(H,...names){const h=H.map(nrm);for(const n of names){const i=h.indexOf(nrm(n));if(i>=0)return i}return-1}
function colContains(H,...terms){const h=H.map(nrm);for(const t of terms){const k=nrm(t);for(let i=0;i<h.length;i++)if(h[i].includes(k))return i}return-1}
function monthInfo(v){return MONTHS[nrm(v)]?{label:MONTHS[nrm(v)][0],month:MONTHS[nrm(v)][1]}:null}
function monthSequence(H){const c=[];for(let i=0;i<H.length;i++){const m=monthInfo(H[i]);if(m)c.push({col:i,dateCol:nrm(H[i+1]).startsWith('DATA')?i+1:null,...m})}let best=[];for(let s=0;s<c.length;s++){let q=[c[s]],p=c[s].month;for(let i=s+1;i<c.length&&q.length<12;i++){const e=p===12?1:p+1;if(c[i].month!==e)break;q.push(c[i]);p=c[i].month}if(q.length>best.length)best=q;if(q.length===12)break}return best.length===12?best:[]}
function isHeaderRow(r){const h=(r||[]).map(nrm);return(h.includes('NOMINATIVO')||h.includes('CONDOMINO'))&&h.includes('RATA')&&monthSequence(r||[]).length===12}
function headerBlocks(rows){const a=[];for(let i=0;i<rows.length;i++)if(isHeaderRow(rows[i]))a.push(i);return a}
function isSummary(name){const x=nrm(name);return!x||x==='TOTALI'||x.startsWith('TOTALE')||x.includes('ANCORA DA INCASSARE')||x.includes('TOTALE DA INCASSARE')||x.includes('TOTALE INCASSI')||x.includes('DA REGISTRARE')}
function pairYear(s){const m=String(s||'').match(/((?:19|20)\d{2})\s*[-_/]\s*(?:(?:19|20)?\d{2,4})/);return m?+m[1]:null}
function sourceYear(s){const str=String(s||'');const p=pairYear(str);if(p)return p;const parts=str.split(/[\\/]/);for(let i=parts.length-1;i>=0;i--){const m=parts[i].match(/\b((?:19|20)\d{2})\b/);if(m)return +m[1]}return null}
function frontYears(wb){const sn=(wb.SheetNames||[]).find(s=>/FRO?NT?ESPIZIO/i.test(s));if(!sn)return[];const txt=rowsOf(wb,sn).slice(0,25).flat().filter(Boolean).join(' '),out=[];for(const m of txt.matchAll(/(?:ESERCIZIO|PERIODO)[^\d]{0,30}((?:19|20)\d{2})/gi))out.push(+m[1]);return[...new Set(out)]}
function resolveExercise(wb,inc,fileName,seq){const src=sourceYear(window.condoSourcePath||fileName),tab=pairYear(inc),front=frontYears(wb),now=new Date().getFullYear();if(src&&src>=now-3&&src<=now+1)return{year:src,warning:tab&&tab!==src?'Riferimento anno del foglio Incassi non coerente con il bilancio selezionato: usato esercizio '+src+'.':''};if(tab&&tab>=now-3&&tab<=now+1)return{year:tab,warning:front.length&&!front.includes(tab)?'Frontespizio non coerente con il foglio Incassi: verificare il documento.':''};return{year:null,warning:'DA VERIFICARE: esercizio contabile non determinabile con certezza.'}}
function assignYears(seq,year){const now=new Date(),sm=seq[0].month;return seq.map((m,i)=>{const a=year*12+sm-1+i,y=Math.floor(a/12),mo=a%12+1;return{...m,year:y,month:mo,due:y<now.getFullYear()||(y===now.getFullYear()&&mo<=now.getMonth()+1)}})}
function frontTitle(wb,fileName){const sn=(wb.SheetNames||[]).find(s=>/FRO?NT?ESPIZIO/i.test(s));if(sn)for(const row of rowsOf(wb,sn).slice(0,10))for(const v of row||[])if(v&&/CONDOMINIO/i.test(String(v)))return String(v).replace(/CONDOMINIO/i,'').replace(/^[ \"-]+|[ \"-]+$/g,'').trim();return String(fileName||'Condominio').replace(/\.(xlsx|xlsm|xls)$/i,'')}
function rateHeaders(rows){const a=[];for(let i=0;i<rows.length;i++){const h=(rows[i]||[]).map(nrm);if((h.includes('NOMINATIVO')||h.includes('CONDOMINO'))&&h.includes('RATA'))a.push(i)}return a}
function fallbackRates(wb){const v=new Map(),d=new Set();for(const sn of wb.SheetNames||[]){if(!/RIPARTO/i.test(sn))continue;const rows=rowsOf(wb,sn),hs=rateHeaders(rows);for(let z=0;z<hs.length;z++){const hi=hs[z],end=z+1<hs.length?hs[z+1]:rows.length,H=headers(rows,hi),nc=colExact(H,'NOMINATIVO','CONDOMINO'),rc=colExact(H,'RATA');if(nc<0||rc<0)continue;for(let j=hi+1;j<end;j++){const name=String(rows[j]?.[nc]??'').trim(),k=canon(name),r=num(rows[j]?.[rc]);if(isSummary(name)||!k||r<=0)continue;if(v.has(k))d.add(k);else v.set(k,r)}}}d.forEach(k=>v.delete(k));return v}
function exactPerson(name,people){const k=canon(name),a=people.filter(x=>canon(x.name)===k);return k&&a.length===1?a[0]:null}
function suspiciousRate(row,months,rata){const vals=months.map(m=>r2(Math.max(0,num(row[m.col])))).filter(v=>v>0);if(vals.length<6)return null;const f=new Map();for(const v of vals)f.set(v,(f.get(v)||0)+1);let mode=0,c=0;for(const[v,n]of f)if(n>c){mode=v;c=n}return c/vals.length>=.75&&Math.abs(mode-r2(rata))>.01?mode:null}
function technicalRow(name,scala,piano,interno){const x=nrm(name);return /\b(CORSIA|ANDRONE|VANO|AREA COMUNE|PARTI COMUNI|LOCALE COMUNE|FONDO CASSA)\b/.test(x)&&!String(scala||'').trim()&&!String(piano||'').trim()&&!String(interno||'').trim()}
function otherHeaders(rows){const a=[];for(let i=0;i<rows.length;i++){const h=(rows[i]||[]).map(nrm);if((h.includes('NOMINATIVO')||h.includes('CONDOMINO'))&&h.some(x=>x.includes('DA INCASSARE')||x.includes('ANCORA DA INCASSARE')||x.includes('CONGUAGLIO')||x.includes('SALDO')||x.includes('IMPORTO')))a.push(i)}return a}
function parseOtherSheet(sn,rows,people){if(!ALLOWED_OTHER.test(nrm(sn)))return;const hs=otherHeaders(rows);let offset=0;for(let z=0;z<hs.length;z++){const hi=hs[z],end=z+1<hs.length?hs[z+1]:rows.length,H=headers(rows,hi),nc=colExact(H,'NOMINATIVO','CONDOMINO');if(nc<0)continue;const bc=colContains(H,'DA INCASSARE','ANCORA DA INCASSARE','RESIDUO','SALDO'),dc=colContains(H,'CONGUAGLIO','IMPORTO','DA VERSARE','TOTALE'),pc=colContains(H,'INCASSATO','PAGATO','VERSATO'),rc=colContains(H,'RIMBORSATO'),cong=/CONG|REC.*INCASS|PRECEDENT/i.test(nrm(sn));let pos=0;for(let j=hi+1;j<end;j++){const row=rows[j],name=String(row?.[nc]??'').trim();if(isSummary(name))continue;const byName=exactPerson(name,people),byRow=people[offset+pos]||null;let p=byName;if(!p&&byRow)p=byRow;if(!p){pos++;continue}if(!byName&&byRow){p._v7.rowMatched=p._v7.rowMatched||[];p._v7.rowMatched.push(sn+': '+name)}let bal=bc>=0?num(row[bc]):0;if(bc<0&&dc>=0)bal=num(row[dc])-(pc>=0?num(row[pc]):0)+(rc>=0?num(row[rc]):0);if(Math.abs(bal)>.01){if(bal>0)p.items.push({type:cong?'cong':'extra',label:cong?'Conguaglio a debito':sn,amount:r2(bal),selected:false});else p.credits.push({label:cong?'Conguaglio / dare-avere a credito':'Credito / eccedenza – '+sn,amount:r2(-bal),selected:false})}pos++}offset+=pos}}
function analyzeV7(wb,fileName){const inc=(wb.SheetNames||[]).find(s=>nrm(s).startsWith('INCASSI')&&!/STRAORD/i.test(nrm(s)));if(!inc)throw Error('Non trovo il foglio Incassi ordinari.');const rows=rowsOf(wb,inc),his=headerBlocks(rows);if(!his.length)throw Error('Non riconosco con sicurezza le intestazioni del foglio '+inc+'.');const fallback=fallbackRates(wb),people=[],blockMonths=[],global=[];
for(let b=0;b<his.length;b++){const hi=his[b],end=b+1<his.length?his[b+1]:rows.length,H=headers(rows,hi),nc=colExact(H,'NOMINATIVO','CONDOMINO'),rc=colExact(H,'RATA'),sc=colExact(H,'SCALA','SC','S'),pc=colExact(H,'P','PIANO'),ic=colExact(H,'INT','INT.','INTERNO'),indc=colContains(H,'SPESE INDIVIDUALI'),indpaid=colContains(H,'RISCOSSIONE','RISCOSSE'),seq=monthSequence(H);if(nc<0||seq.length!==12)continue;const ex=resolveExercise(wb,inc,fileName,seq);if(ex.warning)global.push(ex.warning);const months=ex.year?assignYears(seq,ex.year):[];blockMonths.push(months);
for(let j=hi+1;j<end;j++){const row=rows[j]||[],name=String(row[nc]??'').trim();if(isSummary(name))continue;const scala=sc>=0?String(row[sc]??''):'',piano=pc>=0?String(row[pc]??''):'',interno=ic>=0?String(row[ic]??''):'';let rata=rc>=0?num(row[rc]):0;if(rata<=0)rata=fallback.get(canon(name))||0;const p={id:people.length,name,scala,piano,interno,phone:'',email:'',items:[],credits:[],conflicts:[],recipientAddress:'',_v7:{inc,rata,months,block:b+1,row:j+1}};
if(!ex.year)p.conflicts.push('DA VERIFICARE: esercizio contabile non determinabile; rate ordinarie non calcolate.');else if(technicalRow(name,scala,piano,interno))p.conflicts.push('DA VERIFICARE: voce tecnica/parte comune; nessun insoluto ordinario calcolato automaticamente.');else if(rata<=0)p.conflicts.push('DA VERIFICARE: rata ordinaria non determinabile con certezza.');else{const mode=suspiciousRate(row,months,rata);if(mode!=null)p.conflicts.push('DA VERIFICARE: rata '+r2(rata)+' € ma pagamenti ricorrenti '+mode+' €. Nessun insoluto ordinario calcolato automaticamente.');else for(const m of months){if(!m.due)continue;const paid=Math.max(0,num(row[m.col])),diff=r2(rata-paid);if(Math.abs(diff)>.01)p.items.push({type:'ordinary',label:m.label+' '+m.year,amount:diff,selected:false,_ordinary:true,_negative:diff<0})}}
if(indc>=0){const due=Math.max(0,num(row[indc])),paid=indpaid>=0?Math.max(0,num(row[indpaid])):0,d=r2(due-paid);if(d>.01)p.items.push({type:'extra',label:'Spese individuali',amount:d,selected:false});else if(d<-.01)p.credits.push({label:'Eccedenza spese individuali',amount:r2(-d),selected:false})}people.push(p)}}
for(const sn of wb.SheetNames||[]){const nn=nrm(sn);if(sn===inc||IGNORE.some(x=>nn.includes(x)))continue;parseOtherSheet(sn,rowsOf(wb,sn),people)}people.forEach((p,i)=>{p.id=i;p.items=p.items.map(x=>({...x,selected:false}));p.credits=p.credits.map(x=>({...x,selected:false}));p._v7.gross=r2(p.items.reduce((s,x)=>s+(x.amount>0?x.amount:0),0))});return{title:frontTitle(wb,fileName),people,inc,months:blockMonths[0]||[],blocks:his.length,warnings:[...new Set(global)]}}
const oldRenderPerson=window.renderPerson;if(typeof oldRenderPerson==='function')window.renderPerson=function(p){oldRenderPerson(p);const box=document.getElementById('p'+p.id);if(!box)return;const ord=(p.items||[]).filter(x=>x.type==='ordinary'),sec=[...box.querySelectorAll('.section')].find(s=>(s.querySelector('h4')?.textContent||'').trim()==='Rate ordinarie scoperte');if(sec){const h=sec.querySelector('h4');if(h)h.textContent='Rate ordinarie';[...sec.querySelectorAll('.item')].forEach((el,i)=>{const x=ord[i],amt=el.querySelector('.amt');if(x&&amt&&x.amount<0){amt.textContent='− '+euro(Math.abs(x.amount));amt.style.color='#c62828';amt.style.fontWeight='900'}})}if(p.conflicts?.length){const w=document.createElement('div');w.style.cssText='margin:10px 0;padding:10px;border-radius:10px;background:#fff3cd;color:#7a5200;font-weight:800';w.textContent=p.conflicts.join(' ');box.prepend(w)}};
const oldMessage=window.message;if(typeof oldMessage==='function')window.message=function(p){const condo=building.textContent.trim()||'Condominio';let lines=['Salve, '+condo,'Siamo a ricordarle il versamento delle seguenti rate condominiali.',''];(p.items||[]).filter(x=>x.selected).forEach(x=>lines.push(`• ${x.label}: ${x.amount<0?'− ':''}${euro(Math.abs(x.amount))}`));const c=calc(p);lines.push('',`TOTALE SELEZIONATO: ${c.gross<0?'− ':''}${euro(Math.abs(c.gross))}`);const cc=(p.credits||[]).filter(x=>x.selected);if(cc.length){lines.push('','COMPENSAZIONI SELEZIONATE:');cc.forEach(x=>lines.push(`• ${x.label}: − ${euro(x.amount)}`));lines.push(`NUOVO TOTALE DOPO COMPENSAZIONE: ${c.net<0?'− ':''}${euro(Math.abs(c.net))}`)}lines.push('','Qualora abbia già provveduto, ritenga nullo il presente promemoria.','Saluti');return lines.join('\n')};
async function parseFileV7(file){loader.classList.remove('hidden');results.classList.add('hidden');try{const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array',cellDates:true,cellFormula:true}),r=analyzeV7(wb,file.name);current=r.people;if(!wb.Sheets.Frotespizio){const front=(wb.SheetNames||[]).find(s=>/FRO?NT?ESPIZIO/i.test(s));if(front)wb.Sheets.Frotespizio=wb.Sheets[front];else wb.Sheets.Frotespizio=XLSX.utils.aoa_to_sheet([[r.title]]);if(!wb.SheetNames.includes('Frotespizio'))wb.SheetNames.push('Frotespizio')}render(file.name,wb);building.textContent=r.title;source.textContent='Motore V7 validato · '+r.blocks+' blocchi Incassi · solo rate scadute';const v=document.querySelector('#results .card .muted');if(v)v.textContent=(r.warnings.length?r.warnings.join(' ')+' · ':'')+'Ordine Excel preservato · mese contro stesso mese · dati ambigui = DA VERIFICARE'}catch(e){console.error(e);alert('Controllo bilancio: '+e.message);throw e}finally{loader.classList.add('hidden')}}
window.condoAnalyzeV7=analyzeV7;parseFile=parseFileV7;
})();