(()=>{
'use strict';
const CACHE_KEY='condo_archive_v5';
const UPDATE_KEY='condo_last_update_v5';
const CONTACT_KEY='condo_contacts_v5';
const clone=o=>JSON.parse(JSON.stringify(o));
const q=id=>document.getElementById(id);
function safeParse(key,def){try{return JSON.parse(localStorage.getItem(key)||'')||def}catch(e){return def}}
function saveJSON(key,val){localStorage.setItem(key,JSON.stringify(val))}
function personKey(p){return [String(building?.textContent||''),p.name,p.scala,p.interno].map(x=>String(x??'').trim().toUpperCase()).join('|')}
function getContacts(){return safeParse(CONTACT_KEY,{})}
function getContact(p){return getContacts()[personKey(p)]||{phone:p.phone||'',email:p.email||''}}
function setContact(p,data){const all=getContacts();all[personKey(p)]={phone:String(data.phone||''),email:String(data.email||'')};saveJSON(CONTACT_KEY,all);p.phone=all[personKey(p)].phone;p.email=all[personKey(p)].email}
function getArchive(){return safeParse(CACHE_KEY,{condomini:{}})}
function saveCurrentArchive(fileName){if(typeof current==='undefined'||!Array.isArray(current)||!current.length||!building)return;const title=(building.textContent||'Condominio').trim();const a=getArchive();a.condomini[title]={title,file:fileName||'',updatedAt:new Date().toISOString(),people:clone(current)};saveJSON(CACHE_KEY,a);renderArchiveHome()}
function lastUpdateText(){const d=safeParse(UPDATE_KEY,null);return d?.ts?`Ultimo aggiornamento: <b>${new Date(d.ts).toLocaleString('it-IT')}</b>${d.source?' · '+escapeHtml(d.source):''}`:'Nessun aggiornamento registrato.'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensureHome(){const main=document.querySelector('main');if(!main)return null;let el=q('archiveHome');if(!el){el=document.createElement('div');el.id='archiveHome';el.className='card no-print';main.insertBefore(el,main.firstChild)}return el}
function renderArchiveHome(){const el=ensureHome();if(!el)return;const a=getArchive(),entries=Object.values(a.condomini||{}).sort((x,y)=>x.title.localeCompare(y.title,'it'));const totalPos=entries.reduce((s,x)=>s+(x.people?.length||0),0);el.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><b>Archivio condomini</b><div class="muted">${entries.length} condomini · ${totalPos} posizioni memorizzate</div></div><span class="badge">V5</span></div><div style="margin-top:10px">${entries.length?entries.map(x=>`<button class="secondary" style="width:100%;margin:5px 0;text-align:left" data-open-condo="${escapeHtml(x.title)}"><b>${escapeHtml(x.title)}</b><br><span style="font-size:12px;font-weight:500">${x.people.length} posizioni · aggiornato ${new Date(x.updatedAt).toLocaleString('it-IT')}</span></button>`).join(''):'<div class="muted">L’archivio verrà popolato dagli Excel. Quando collegheremo Condomini_APP online, AGGIORNA lo farà automaticamente dal telefono.</div>'}</div>`;el.querySelectorAll('[data-open-condo]').forEach(b=>b.addEventListener('click',()=>openCached(b.dataset.openCondo)))}
function openCached(title){const rec=getArchive().condomini?.[title];if(!rec)return;current=clone(rec.people||[]);current.forEach((p,i)=>p.id=i);building.textContent=rec.title;source.textContent=`Archivio memorizzato${rec.file?' · '+rec.file:''} · ${new Date(rec.updatedAt).toLocaleString('it-IT')}`;people.innerHTML='';current.forEach(p=>{const el=document.createElement('details');el.className='person';const bad=p.conflicts&&p.conflicts.length;el.innerHTML=`<summary><span style="${bad?'color:#c62828;font-weight:900':''}">${escapeHtml(p.name)}</span> <span class="badge">Scala ${escapeHtml(p.scala)} · Int. ${escapeHtml(p.interno)}</span>${bad?' <span style="color:#c62828">⚠</span>':''}</summary><div class="body" id="p${p.id}"></div>`;people.appendChild(el);renderPerson(p)});results.classList.remove('hidden');loadConfig();window.scrollTo({top:results.offsetTop-70,behavior:'smooth'})}
function setupUpdateCard(){const btn=q('folderBtn');if(!btn)return;btn.textContent='AGGIORNA';btn.style.width='100%';btn.style.fontSize='17px';btn.style.padding='14px';const card=btn.closest('.card');if(card?.querySelector('b'))card.querySelector('b').textContent='Aggiornamento dati';const p=card?.querySelector('p.muted');if(p)p.innerHTML='Il pulsante <b>AGGIORNA</b> sarà collegato alla cartella online <b>Condomini_APP</b>. Fino al collegamento finale resta disponibile la selezione manuale della cartella/Excel come modalità di prova.';let info=q('v5UpdateInfo');if(!info&&card){info=document.createElement('div');info.id='v5UpdateInfo';info.className='muted';info.style.marginTop='8px';card.appendChild(info)}if(info)info.innerHTML=lastUpdateText();const oldOpen=q('openSelected');if(oldOpen)oldOpen.textContent='Apri e aggiorna condominio'}
function injectContactFields(p){const box=q('p'+p.id);if(!box||box.querySelector('.v5contacts'))return;const c=getContact(p);p.phone=c.phone||p.phone||'';p.email=c.email||'';const actions=box.querySelector('.actions');if(!actions)return;const wrap=document.createElement('div');wrap.className='v5contacts';wrap.style.cssText='margin-top:12px;padding:10px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px';wrap.innerHTML=`<b>Contatti condomino</b><div class="row" style="margin-top:7px"><input class="v5phone" type="tel" placeholder="Numero WhatsApp" value="${escapeHtml(p.phone||'')}"><input class="v5email" type="email" placeholder="Email condomino" value="${escapeHtml(p.email||'')}"></div><button class="secondary v5rubrica" style="width:100%;margin-top:7px">📇 Rubrica telefono</button>`;actions.parentNode.insertBefore(wrap,actions);const ph=wrap.querySelector('.v5phone'),em=wrap.querySelector('.v5email');const persist=()=>setContact(p,{phone:ph.value,email:em.value});ph.addEventListener('change',persist);em.addEventListener('change',persist);wrap.querySelector('.v5rubrica').addEventListener('click',async()=>{try{if(!navigator.contacts?.select){alert('La selezione diretta dalla rubrica non è supportata da questo browser. Puoi inserire il numero manualmente.');return}const r=await navigator.contacts.select(['name','tel','email'],{multiple:false});if(r?.[0]){if(r[0].tel?.[0])ph.value=r[0].tel[0];if(r[0].email?.[0])em.value=r[0].email[0];persist()}}catch(e){alert('Non riesco ad aprire la rubrica: '+e.message)}})}
function patchFunctions(){if(typeof render==='function'){const originalRender=render;render=function(fileName,wb){originalRender(fileName,wb);saveCurrentArchive(fileName);saveJSON(UPDATE_KEY,{ts:new Date().toISOString(),source:fileName||'Excel'});const i=q('v5UpdateInfo');if(i)i.innerHTML=lastUpdateText();current.forEach(injectContactFields)}}if(typeof renderPerson==='function'){const originalRP=renderPerson;renderPerson=function(p){originalRP(p);injectContactFields(p)}}if(typeof whatsapp==='function'){whatsapp=function(id){let p=current[id],c=calc(p),ct=getContact(p);p.phone=ct.phone||p.phone||'';if(!String(p.phone||'').replace(/\D/g,'')){alert('Inserisci prima il numero WhatsApp del condomino.');return}addHistory(p,'WhatsApp - apertura invio',c.net);location.href=`https://wa.me/${String(p.phone).replace(/\D/g,'')}?text=${encodeURIComponent(message(p))}`}}if(typeof emailOne==='function'){emailOne=function(id){let p=current[id],c=calc(p),ct=getContact(p);if(!ct.email){alert('Inserisci prima l’email del condomino.');return}addHistory(p,'Email - apertura invio',c.net);let subj=`Sollecito quote condominiali - ${building.textContent.trim()} - ${p.name}`;location.href=`mailto:${encodeURIComponent(ct.email)}?subject=${encodeURIComponent(subj)}&body=${encodeURIComponent(message(p))}`}}}
function setup(){document.title='Gestione Condomini';const h=document.querySelector('header h1');if(h)h.textContent='🏢 Gestione Condomini';document.querySelectorAll('header div').forEach(el=>{if(el.textContent.includes('V2.8')||el.textContent.includes('V4'))el.textContent='Morosità · selezione voci · compensazioni · WhatsApp · Email · Messa in mora'});setupUpdateCard();patchFunctions();renderArchiveHome();if(typeof current!=='undefined'&&Array.isArray(current))current.forEach(injectContactFields)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();